import { Grid, GridItem } from '@chakra-ui/react';

const AboutGrid = () => {
  return (
    <Grid
      h="100%"
      w="100%"
      templateRows="repeat(5, 1fr)"
      templateColumns="repeat(5, 1fr)"
      gap={4}
      zIndex={10}
    >
      <GridItem
        bgImage="url(/about-grid-1.png)"
        bgSize="cover"
        filter="grayscale(1)"
      />
      <GridItem
        bgImage="url(/about-grid-1.png)"
        bgSize="cover"
        filter="grayscale(1)"
      />
      <GridItem
        bgImage="url(/about-grid-1.png)"
        bgSize="cover"
        filter="grayscale(1)"
      />
      <GridItem
        bgImage="url(/about-grid-1.png)"
        bgSize="cover"
        filter="grayscale(1)"
      />
      <GridItem
        bgImage="url(/about-grid-1.png)"
        bgSize="cover"
        filter="grayscale(1)"
      />
      <GridItem
        bgImage="url(/about-grid-1.png)"
        bgSize="cover"
        filter="grayscale(1)"
      />
      <GridItem
        bgImage="url(/about-grid-1.png)"
        bgSize="cover"
        filter="grayscale(1)"
      />
      <GridItem
        bgImage="url(/about-grid-1.png)"
        bgSize="cover"
        filter="grayscale(1)"
      />
      <GridItem
        bgImage="url(/about-grid-1.png)"
        bgSize="cover"
        filter="grayscale(1)"
      />
      <GridItem
        bgImage="url(/about-grid-1.png)"
        bgSize="cover"
        filter="grayscale(1)"
      />
      <GridItem
        bgImage="url(/about-grid-1.png)"
        bgSize="cover"
        filter="grayscale(1)"
      />
      <GridItem
        bgImage="url(/about-grid-1.png)"
        bgSize="cover"
        filter="grayscale(1)"
      />
      <GridItem
        bgImage="url(/about-grid-1.png)"
        bgSize="cover"
        filter="grayscale(1)"
      />
      <GridItem
        bgImage="url(/about-grid-1.png)"
        bgSize="cover"
        filter="grayscale(1)"
      />
      <GridItem
        bgImage="url(/about-grid-1.png)"
        bgSize="cover"
        filter="grayscale(1)"
      />
      <GridItem
        bgImage="url(/about-grid-1.png)"
        bgSize="cover"
        filter="grayscale(1)"
      />
      <GridItem
        bgImage="url(/about-grid-1.png)"
        bgSize="cover"
        filter="grayscale(1)"
      />
      <GridItem
        bgImage="url(/about-grid-1.png)"
        bgSize="cover"
        filter="grayscale(1)"
      />
      <GridItem
        bgImage="url(/about-grid-1.png)"
        bgSize="cover"
        filter="grayscale(1)"
      />
      <GridItem
        bgImage="url(/about-grid-1.png)"
        bgSize="cover"
        filter="grayscale(1)"
      />
      <GridItem
        bgImage="url(/about-grid-1.png)"
        bgSize="cover"
        filter="grayscale(1)"
      />
      <GridItem
        bgImage="url(/about-grid-1.png)"
        bgSize="cover"
        filter="grayscale(1)"
      />
      <GridItem
        bgImage="url(/about-grid-1.png)"
        bgSize="cover"
        filter="grayscale(1)"
      />
      <GridItem
        bgImage="url(/about-grid-1.png)"
        bgSize="cover"
        filter="grayscale(1)"
      />
      <GridItem
        bgImage="url(/about-grid-1.png)"
        bgSize="cover"
        filter="grayscale(1)"
      />
    </Grid>
  );
};
export default AboutGrid;
